draft versio

diff --git a/rgbenv b/rgbenv
--- a/rgbenv
+++ b/rgbenv
@@ -22,6 +22,8 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+set -euo pipefail
+
 # --------------- Constant defines -------------------------------------------------
 
 RGBDS_GIT="https://github.com/gbdev/rgbds"
@@ -30,24 +32,27 @@ RGBDS_GIT="https://github.com/gbdev/rgbds"
 RGBDS_DOWNLOAD_BASE="https://api.github.com/repos/gbdev/rgbds/tarball/"
 RGBDS_PREFIX="rgbds-"
 
+RGBDS_PREFIX_LEN="${#RGBDS_PREFIX}"
+RGBENV_ROOT_SUFFIX="rgbenv"
+
 # --------------- Conditional defines -------------------------------------------------
 
 # Set up XDG standard directories (Linux, etc.)
-RGBENV_ROOT_SUFFIX="rgbenv"
 
-RGBENV_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/$RGBENV_ROOT_SUFFIX"
+RGBENV_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/${RGBENV_ROOT_SUFFIX}"
 if [[ ! -d "${XDG_DATA_HOME:-$HOME/.local/share}" ]]; then
 	RGBENV_ROOT="$HOME/.$RGBENV_ROOT_SUFFIX"
 fi
 
-RGBENV_DEFAULT="$RGBENV_ROOT/default"
-RGBENV_VERSIONS="$RGBENV_ROOT/versions"
+RGBENV_DEFAULT="${RGBENV_ROOT}/default"
+RGBENV_VERSIONS="${RGBENV_ROOT}/versions"
 
-RGBDS_PREFIX_LEN="${#RGBDS_PREFIX}"
-
-# available offline
-if [ -d "$RGBENV_VERSIONS" ]; then
-	AVAILABLE_VERSIONS=$(find "$RGBENV_VERSIONS" -maxdepth 1 -type d | grep -Eo "${RGBDS_PREFIX}[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9_]+)?")
+# find versions already installed
+if [ -d "${RGBENV_VERSIONS}" ]; then
+	AVAILABLE_VERSIONS=$(
+		find "${RGBENV_VERSIONS}" -maxdepth 1 -mindepth 1 -type d | \
+		awk -F/ '{print $NF;}'
+	)
 else
 	AVAILABLE_VERSIONS=''
 fi
@@ -55,8 +60,16 @@ fi
 # --------------- Helpers ----------------------------------------------------
 
 check_online_versions () {
-	# set the relevant variable
-	ONLINE_VERSIONS=$(git ls-remote --tags "$RGBDS_GIT" | grep -Eo "[0-9]+.[0-9]+.[0-9]+(-[A-Za-z0-9_]+)?$")
+	ONLINE_VERSIONS="
+	$(
+		git ls-remote --tags "${RGBDS_GIT}" | \
+		awk '{
+			sub(/.+\^\{\}|^refs\/tags\/v?/, "", $2);
+			print $2
+		}'
+	)
+		master
+	"
 }
 
 help () {
@@ -93,14 +106,17 @@ help () {
 	echo
 	echo "    remove"
 	echo "        Removes the rgbenv directories."
+	echo
+	echo "    activate [-]"
+	echo "        Opens the current shell with the rgbenv"
+	echo "        environment appended to \$PATH. Use - to"
+	echo "        print out the shell commands, for use as"
+	echo "        e.g. eval rgbenv activate -."
 }
 
 checkver () {
-	if [ -z "$1" ]; then
+	if [ -z "${1}" ]; then
 		echo "No version number set!"
-		point_to_available_command_and_terminate
-	elif [[ ! $1 =~ [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-[A-Za-z0-9_]+)? ]]; then
-		echo "Invalid version number."
 		point_to_available_command_and_terminate
 	fi
 }
@@ -108,27 +124,27 @@ checkver () {
 checkverinstall () {
 	local version=$1
 	local has_choice=0
-	checkver "$version";
-	if [ -d "$RGBENV_VERSIONS/$RGBDS_PREFIX$version" ]; then
-		while [ $has_choice -eq 0 ]; do
-			read -p "Version $version is already installed. Do you want to reinstall? [y/n] " choice
-			case $choice in
+	checkver "${version}";
+	if [ -d "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}" ]; then
+		while [ ${has_choice} -eq 0 ]; do
+			read -p "Version ${version} is already installed. Do you want to reinstall? [y/n] " choice
+			case ${choice} in
 				[Yy]* ) has_choice=1; rm -r "${RGBENV_VERSIONS:?}/${RGBDS_PREFIX:?}${version:?}"; break;;
 				[Nn]* ) exit; break;;
 				* ) echo "Please answer y or n.";;
 			esac
 		done
 	else
-		echo "Version $version isn't installed yet."
+		echo "Version ${version} isn't installed yet."
 	fi
 }
 
 _remove () {
 	local has_choice=0
-	while [ $has_choice -eq 0 ]; do
+	while [ ${has_choice} -eq 0 ]; do
 		read -p "Remove rgbenv directories? [y/n] " choice
-		case $choice in
-			[Yy]* ) rm -rfv "$RGBENV_ROOT"; has_choice=1; break;;
+		case ${choice} in
+			[Yy]* ) rm -rfv "${RGBENV_ROOT:?}"; has_choice=1; break;;
 			[Nn]* ) has_choice=1; exit;;
 			* ) echo "Please answer y or n.";;
 		esac
@@ -138,13 +154,13 @@ _remove () {
 offer_to_move () {
 	local has_choice=0
 	echo "XDG_DATA_HOME defined, but there's an existing rgbenv"
-	echo "installation at $HOME/.$RGBENV_ROOT_SUFFIX."
+	echo "installation at ${HOME}/.${RGBENV_ROOT_SUFFIX}."
 	echo "Moving the existing installation seems like a good idea:"
-	echo "    $HOME/.$RGBENV_ROOT_SUFFIX -> $RGBENV_ROOT"
+	echo "    ${HOME}/.${RGBENV_ROOT_SUFFIX} -> ${RGBENV_ROOT}"
 	echo
-	while [ $has_choice -eq 0 ]; do
+	while [ ${has_choice} -eq 0 ]; do
 		read -p "Would you like to move these directories? [y/n] " choice
-		case $choice in
+		case ${choice} in
 			[Yy]* ) move_dirs; has_choice=1; break;;
 			[Nn]* ) has_choice=1; exit;;
 			* ) echo "Please answer y or n.";;
@@ -153,17 +169,17 @@ offer_to_move () {
 }
 
 move_dirs () {
-	mv "$HOME/.$RGBENV_ROOT_SUFFIX" "$RGBENV_ROOT"
+	mv "${HOME}/.${RGBENV_ROOT_SUFFIX}" "${RGBENV_ROOT}"
 }
 
 setup () {
 	local has_choice=0
 	echo "rgbenv has not been set up yet."
 	echo "The following operations will be done:"
-	echo "    Create rgbenv defaults dir     -> $RGBENV_DEFAULT"
-	echo "    Create source and binaries dir -> $RGBENV_VERSIONS"
+	echo "    Create rgbenv defaults dir     -> ${RGBENV_DEFAULT}"
+	echo "    Create source and binaries dir -> ${RGBENV_VERSIONS}"
 	echo
-	while [ $has_choice -eq 0 ]; do
+	while [ ${has_choice} -eq 0 ]; do
 		read -p "Would you like to do that now? [y/n] " choice
 		case $choice in
 			[Yy]* ) make_dirs; has_choice=1; break;;
@@ -174,14 +190,14 @@ setup () {
 }
 
 make_dirs () {
-	mkdir -p "$RGBENV_DEFAULT"
-	mkdir -p "$RGBENV_VERSIONS"
+	mkdir -p "${RGBENV_DEFAULT}"
+	mkdir -p "${RGBENV_VERSIONS}"
 }
 
 show_install_instructions () {
 	echo
 	echo "You can try to install this version by:"
-	echo "    rgbenv install $1"
+	echo "    rgbenv install ${1}"
 }
 
 point_to_available_command_and_terminate () {
@@ -208,18 +224,18 @@ point_to_use_and_terminate () {
 # --------------- Subcommands -----------------------------------------
 
 _available () {
-	if [ "$#" -gt 0 ] && [ "$1" == "--online" ]; then
+	if [ "$#" -gt 0 ] && [ "${1}" == "--online" ]; then
 		check_online_versions
 		echo "Installable versions:"
-		for i in $ONLINE_VERSIONS; do
-			echo "    $i"
+		for i in ${ONLINE_VERSIONS}; do
+			echo "    ${i}"
 		done
 	
 	else
 	
-		local have_versions=$AVAILABLE_VERSIONS
+		local have_versions=${AVAILABLE_VERSIONS}
 		
-		if [ -z "$have_versions" ]; then
+		if [ -z "${have_versions}" ]; then
 			echo "There are no versions currently installed."
 			echo "Look at the available versions using:"
 			echo "    rgbenv available --online"
@@ -230,10 +246,10 @@ _available () {
 			exit 1
 		else
 			echo "Currently installed versions:"
-			for i in $have_versions; do
+			for i in ${have_versions}; do
 			# Versions prefixed with "rgbds-", cut them off
-				i=$(echo "$i" | cut -c$(( $RGBDS_PREFIX_LEN + 1 ))-)
-				echo "    $i"
+				i=$(echo "${i}" | cut -c$(( ${RGBDS_PREFIX_LEN} + 1 ))-)
+				echo "    ${i}"
 			done
 		fi
 		
@@ -242,49 +258,60 @@ _available () {
 
 _use () {
 	if [ "$#" -lt 1 ]; then
-		if [ -f "$RGBENV_DEFAULT/version" ]; then
-			cat "$RGBENV_DEFAULT/version"
+		if [ -f "${RGBENV_DEFAULT}/version" ]; then
+			cat "${RGBENV_DEFAULT}/version"
 		else
 			echo "Use which version?"
 			point_to_available_command_and_terminate
 		fi
 	else
-		checkver "$1";
+		checkver "${1}";
+		
 		# check if we have a working build of RGBASM (at the very least)
-		if [ -x "$RGBENV_VERSIONS/$RGBDS_PREFIX$1/rgbasm" ]; then
-			# create symlinks to the proper RGBDS version
-			mkdir -p "$RGBENV_DEFAULT/bin"
+		local rgbasm_cur_ver="${RGBENV_VERSIONS}/${RGBDS_PREFIX}${1}/rgbasm"
+		
+		if [ -x "${rgbasm_cur_ver}" ]; then
+			# `rgbasm -V` doesn't work on the earliest versions,
+			# can't check for it that way. Invoking `rgbasm` returns 1.
 			
-			echo "Making symlinks..."
-			for i in rgbasm rgblink rgbfix rgbgfx; do
-				ln -sf "$RGBENV_VERSIONS/$RGBDS_PREFIX$1/$i" "$RGBENV_DEFAULT/bin/$i"
+			# create symlinks to the proper RGBDS version
+			mkdir -p "${RGBENV_DEFAULT}/bin"
+			echo "Making symlinks for:"
+			for i in rgbasm rgblink rgbfix rgbgfx rgblib; do
+				local from="${RGBENV_VERSIONS}/${RGBDS_PREFIX}${1}/${i}"
+				local to="${RGBENV_DEFAULT}/bin/${i}"
+				
+				if [ -f "${from}" ]; then
+					echo "    ...${i}"
+					ln -sf "${from}" "${to}"
+				fi
 			done
 			echo
 			
-			echo "$1" > "$RGBENV_DEFAULT/version"
+			echo "${1}" > "${RGBENV_DEFAULT}/version"
 			
-			echo "The default RGBDS has been set to $1."
-			if [[ ":$PATH:" != *":$RGBENV_DEFAULT/bin:"* ]]; then
+			echo "The default RGBDS has been set to ${1}."
+			if [[ ":${PATH}:" != *":${RGBENV_DEFAULT}/bin:"* ]]; then
 				echo "To use it, ensure that the following is in your shell configuration:"
 				echo
-				echo "export PATH=\"$RGBENV_DEFAULT/bin:\$PATH\""
+				echo "export PATH=\"${RGBENV_DEFAULT}/bin:\${PATH}\""
 				echo
 				echo "Once that's done, restart your shell and"
 				echo "verify with rgbasm -V."
 			fi
 		else
-			echo "Version $1 has not been installed yet."
-			show_install_instructions "$1"
+			echo "Version ${1} has not been installed yet."
+			show_install_instructions "${1}"
 			point_to_available_command_and_terminate
 		fi
 	fi
 }
 
 _no_use () {
-	if [ -f "$RGBENV_DEFAULT/version" ]; then
+	if [ -f "${RGBENV_DEFAULT}/version" ]; then
 		rm "${RGBENV_DEFAULT:?}/version"
 	fi
-	if [ -d "$RGBENV_DEFAULT/bin" ]; then
+	if [ -d "${RGBENV_DEFAULT}/bin" ]; then
 		rm -r "${RGBENV_DEFAULT:?}/bin"
 	fi
 	echo "Symlinks and version configuration deleted."
@@ -304,50 +331,57 @@ _install () {
 	local version=$1
 	local got_version=0
 	local download_link
-	if [[ "$version" =~ ^[0-9] ]]; then
+	if [[ "${version}" =~ ^[0-9] ]]; then
 		download_link="${RGBDS_DOWNLOAD_BASE}v${version}"
 	else
 		download_link="${RGBDS_DOWNLOAD_BASE}${version}"
 	fi
 	
-	checkverinstall "$version"
+	local download_link
+	if [[ "${version}" =~ ^[0-9] ]]; then
+		download_link="${RGBDS_DOWNLOAD_BASE}v${version}"
+	else
+		download_link="${RGBDS_DOWNLOAD_BASE}${version}"
+	fi
+	
+	checkverinstall "${version}"
 	
 	check_online_versions
-	local available="$ONLINE_VERSIONS"
+	local available="${ONLINE_VERSIONS}"
 	
 	# check if the version we want is in the git version tags list
 	for i in $available; do
-		if [ "$version" = "$i" ]; then
+		if [ "${version}" = "${i}" ]; then
 			got_version=1
 			continue
 		fi
 	done
-	if [ $got_version -eq 0 ]; then
-		echo "Version $version not found in the releases page."
+	if [ ${got_version} -eq 0 ]; then
+		echo "Version ${version} not found in the releases page."
 		point_to_available_online_and_terminate
 	fi
 	
 	# if so, download the tarball and extract it
-	echo "Downloading from $download_link..."
+	echo "Downloading from ${download_link:?}..."
 	tempfile=$(mktemp)
-	trap "rm -f \"${tempfile}\"" ERR
-	curl -L "$download_link" > "$tempfile"
+	trap "rm -f \"${tempfile:?}\"" ERR
+	curl -L "${download_link}" > "${tempfile}"
 	dirname=$(tar tzf "$tempfile" | head -1 | cut -f1 -d'/')
-	cd "$RGBENV_VERSIONS"
-	tar xzf "$tempfile"
+	cd "${RGBENV_VERSIONS}"
+	tar xzf "${tempfile}"
 	
-	mv "$RGBENV_VERSIONS/$dirname" "$RGBENV_VERSIONS/$RGBDS_PREFIX$version"
+	mv "${RGBENV_VERSIONS}/${dirname}" "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}"
 	trap - ERR
-	rm -f "${tempfile}"
+	rm -f "${tempfile:?}"
 	
 	# then build it
-	echo "Building RGBDS $version..."
-	cd "$RGBENV_VERSIONS/$RGBDS_PREFIX$version"
+	echo "Building RGBDS ${version}..."
+	cd "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}"
 	if make; then
 		echo "Build successful."
 		echo
 		echo "You can now use this version by:"
-		echo "    rgbenv use $version"
+		echo "    rgbenv use ${version}"
 	else
 		echo "One or more build components failed! You may still use this"
 		echo "version, just with missing tools."
@@ -362,62 +396,62 @@ _uninstall () {
 	fi
 	
 	local version=$1
-		checkver "$version"
-		if [ -d "$RGBENV_VERSIONS/$RGBDS_PREFIX$version" ]; then
+		checkver "${version}"
+		if [ -d "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}" ]; then
 			rm -r "${RGBENV_VERSIONS:?}/${RGBDS_PREFIX:?}${version:?}"
 			
-			if [ -d "$RGBENV_DEFAULT/version" ]; then
-				if [ "$(cat "$RGBENV_DEFAULT/version")" = "$version" ]; then
+			if [ -d "$RGBENV_DEFAULT/{version}" ]; then
+				if [ "$(cat "${RGBENV_DEFAULT}/version")" = "${version}" ]; then
 					rm "${RGBENV_DEFAULT:?}/version"
 					rm "${RGBENV_DEFAULT:?}/bin/*"
 					echo "Removed current RGBDS version, RGBDS is now system-managed"
 				fi
 			fi
-			echo "Version $1 uninstalled."
+			echo "Version ${1} uninstalled."
 			
 		fi
 }
 
 _exec () {
-	if [ "$1" == "--version" ] || [ "$1" == "-v" ] ; then
+	if [ "${1}" == "--version" ] || [ "${1}" == "-v" ] ; then
 		shift
 		local version=$1
-		checkver "$version"
-		if [ -x "$RGBENV_VERSIONS/$RGBDS_PREFIX$version/rgbasm" ]; then
+		checkver "${version}"
+		if [ -x "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}/rgbasm" ]; then
 			shift
 			if [ ${#@} -gt 0 ]; then
-				echo "Executing with RGBDS version $version."
-				env PATH="$RGBENV_VERSIONS/$RGBDS_PREFIX$version:$PATH" "$@"
+				echo "Executing with RGBDS version ${version}."
+				env PATH="${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}:${PATH}" "${@}"
 			fi
 		else
-			echo "Version $version is not installed."
-			show_install_instructions "$version"
+			echo "Version ${version} is not installed."
+			show_install_instructions "${version}"
 			point_to_available_command_and_terminate
 		fi
 	elif [ -f .rgbds-version ]; then
 		local version=$(tr -d " \t\n\r" < .rgbds-version)
-		checkver "$version"
-		if [ -x "$RGBENV_VERSIONS/$RGBDS_PREFIX$version/rgbasm" ]; then
+		checkver "${version}"
+		if [ -x "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}/rgbasm" ]; then
 			if [ ${#@} -gt 0 ]; then
-				echo "Executing with RGBDS version $version."
-				env PATH="$RGBENV_VERSIONS/$RGBDS_PREFIX$version:$PATH" "$@"
+				echo "Executing with RGBDS version ${version}."
+				env PATH="${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}:${PATH}" "$@"
 			fi
 		else
-			echo "Version $version is not installed."
-			show_install_instructions "$version"
+			echo "Version ${version} is not installed."
+			show_install_instructions "${version}"
 			point_to_available_command_and_terminate
 		fi
 	else
 		# when PATH is set properly, this would pretty much be useless
 		# This *does* have a use if it isn't though
-		if [ -f "$RGBENV_DEFAULT/version" ]; then
-			version=$(cat "$RGBENV_DEFAULT/version")
-			if [ ! -x "$RGBENV_VERSIONS/$RGBDS_PREFIX$version/rgbasm" ]; then
+		if [ -f "${RGBENV_DEFAULT}/version" ]; then
+			version=$(cat "${RGBENV_DEFAULT}/version")
+			if [ ! -x "${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}/rgbasm" ]; then
 				echo "Version not set."
 				point_to_use_and_terminate
 			else
 				if [ ${#@} -gt 0 ]; then
-					env PATH="$RGBENV_VERSIONS/$RGBDS_PREFIX$version:$PATH" "$@"
+					env PATH="${RGBENV_VERSIONS}/${RGBDS_PREFIX}${version}:${PATH}" "${@}"
 				fi
 			fi
 		else
@@ -430,8 +464,8 @@ _exec () {
 # --------------- Entry point -------------------------------------------------
 
 # Perform setup
-if [ ! -d "$RGBENV_DEFAULT" ]; then
-	if [ -d "$HOME/.$RGBENV_ROOT_SUFFIX" ]; then
+if [ ! -d "${RGBENV_DEFAULT}" ]; then
+	if [ -d "${HOME}/.${RGBENV_ROOT_SUFFIX}" ]; then
 		offer_to_move
 	else
 		setup
@@ -450,6 +484,7 @@ else
 		exec* ) shift; _exec "$@";;
 		available* ) shift; _available "$@";;
 		remove*) shift; _remove;;
+		activate*) shift; _activate;;
 		*) echo -e "Unknown command $1.\n"; help;;
 	esac
 fi
